// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6VYL3AN87D_EcRB8nYmdojKiJc6VcvK0',
    appId: '1:414107147801:web:937fc450961a8a41695488',
    messagingSenderId: '414107147801',
    projectId: 'drugland-app',
    authDomain: 'drugland-app.firebaseapp.com',
    storageBucket: 'drugland-app.appspot.com',
    measurementId: 'G-TKZW0EWD6Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyHpiFrtKo_rTrAHCp_9GwrWzHn1bnIjI',
    appId: '1:414107147801:android:f1b463a9022cbd24695488',
    messagingSenderId: '414107147801',
    projectId: 'drugland-app',
    storageBucket: 'drugland-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcatpnooMm_TjZkX_YVgKWC11S2zI6ZkQ',
    appId: '1:414107147801:ios:d5bc299188ded82c695488',
    messagingSenderId: '414107147801',
    projectId: 'drugland-app',
    storageBucket: 'drugland-app.appspot.com',
    iosClientId: '414107147801-kmds12rk0ab08b193521pas1fqbul620.apps.googleusercontent.com',
    iosBundleId: 'com.example.druglandApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcatpnooMm_TjZkX_YVgKWC11S2zI6ZkQ',
    appId: '1:414107147801:ios:d5bc299188ded82c695488',
    messagingSenderId: '414107147801',
    projectId: 'drugland-app',
    storageBucket: 'drugland-app.appspot.com',
    iosClientId: '414107147801-kmds12rk0ab08b193521pas1fqbul620.apps.googleusercontent.com',
    iosBundleId: 'com.example.druglandApp',
  );
}
